### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'None' has no attribute 'meta'

### ISSUE THREAD

**Issue by ozbek** [zhaoterryy/mkdocs-git-revision-date-plugin#1]
I followed the instructions in the README, but got `'None' has no attribute 'meta'` error during build.

<details>
<summary>Full log (click to expand):</summary>
<p>

```
$ mkdocs build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: app/templates/docs
Traceback (most recent call last):
  File "env/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "env/lib/python3.6/site-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "env/lib/python3.6/site-packages/mkdocs/commands/build.py", line 288, in build
    _build_theme_template(template, env, files, config, nav)
  File "env/lib/python3.6/site-packages/mkdocs/commands/build.py", line 117, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "env/lib/python3.6/site-packages/mkdocs/commands/build.py", line 96, in _build_template
    output = template.render(context)
  File "env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "env/lib/python3.6/site-packages/mkdocs/themes/readthedocs/search.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "env/lib/python3.6/site-packages/mkdocs/themes/readthedocs/base.html", line 118, in top-level template code
    {%- block footer %}
  File "env/lib/python3.6/site-packages/mkdocs/themes/readthedocs/base.html", line 119, in block "footer"
    {% include "footer.html" %}
  File "markdown/custom_theme/footer.html", line 27, in top-level template code
    <br><i>Updated {{ page.meta.revision_date }}</i>
  File "env/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'meta'
```

</p>
</details>

As can be sean from stack trace, I am using readthedocs theme and have `footer.html` file in custom_theme dir:

```
plugins:
  - search
  - git-revision-date
theme:
  name: readthedocs
  custom_dir: custom_theme/
```

<details>
<summary>footer.html (click to expand):</summary>
<p>

```
<footer>
  {%- block next_prev %}
  {% if config.theme.prev_next_buttons_location|lower in ['bottom', 'both']
        and page and (page.next_page or page.previous_page) %}
    <div class="rst-footer-buttons" role="navigation" aria-label="footer navigation">
      {% if page.next_page %}
        <a href="{{ page.next_page.url|url }}" class="btn btn-neutral float-right" title="{{ page.next_page.title }}">Next <span class="icon icon-circle-arrow-right"></span></a>
      {% endif %}
      {% if page.previous_page %}
        <a href="{{ page.previous_page.url|url }}" class="btn btn-neutral" title="{{ page.previous_page.title }}"><span class="icon icon-circle-arrow-left"></span> Previous</a>
      {% endif %}
    </div>
  {% endif %}
  {%- endblock %}

  <hr/>

  <div role="contentinfo">
    <!-- Copyright etc -->
    {% if config.copyright %}
      <p><small>{{ config.copyright }}</small></p>
    {% endif %}
  </div>

  <small>
    Built with <a href="https://www.mkdocs.org/">MkDocs</a> using a <a href="https://github.com/snide/sphinx_rtd_theme">theme</a> provided by <a href="https://readthedocs.org">Read the Docs</a>.
    <br><i>Updated {{ page.meta.revision_date }}</i>
  </small>
</footer>
```

</p>
</details>

**Where am I doing wrong?**

**Comment by zhaoterryy** [comment]
Try wrapping it like so, since it's error due to page being 'None'.

```
    {% if page and page.meta.revision_date %}
        <br><i>Updated {{ page.meta.revision_date }}</i>
    {% endif %}
```

**Comment by ozbek** [comment]
Yay, that worked! Thanks :+1:
