### ISSUE TITLE
cannot run mkdocs build

### ISSUE THREAD

**Issue by profy12** [zhaoterryy/mkdocs-git-revision-date-plugin#9]
Is this plugin work with private github repository ?

When I try to build mkdocs, I have this message : 

`jinja2.exceptions.UndefinedError: 'secrets' is undefined`

Full log :

```
ERROR   -  Error reading page 'deviens.dev---hébergement.md': 'secrets' is undefined 
Traceback (most recent call last):
  File "/home/profy/.ve-mkdocs-python3/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/profy/.ve-mkdocs-python3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/profy/.ve-mkdocs-python3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/profy/.ve-mkdocs-python3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/profy/.ve-mkdocs-python3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/profy/.ve-mkdocs-python3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/profy/.ve-mkdocs-python3/lib/python3.6/site-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/home/profy/.ve-mkdocs-python3/lib/python3.6/site-packages/mkdocs/commands/build.py", line 274, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/profy/.ve-mkdocs-python3/lib/python3.6/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    'page_markdown', page.markdown, page=page, config=config, files=files
  File "/home/profy/.ve-mkdocs-python3/lib/python3.6/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/home/profy/.ve-mkdocs-python3/lib/python3.6/site-packages/mkdocs_git_revision_date_plugin/plugin.py", line 59, in on_page_markdown
    return md_template.render({'git_revision_date': revision_date})
  File "/home/profy/.ve-mkdocs-python3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/profy/.ve-mkdocs-python3/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/profy/.ve-mkdocs-python3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/profy/.ve-mkdocs-python3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 103, in top-level template code
  File "/home/profy/.ve-mkdocs-python3/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'secrets' is undefined
```

**Comment by koweblomke** [comment]
I had the same issue, but it was related to the mkdocs-macros-plugin.
When I dissabled that plugin the error disappeared.
This happened to me because I had some example Jinja templates in my documentation which were tried to be rendered.

**Comment by profy12** [comment]
I'm not using macros plugins only the search one.

I'm using mkdocs material maybe it's related ...

**Comment by timvink** [comment]
The problem is this plugin uses `jinja2.Theme().render()` (see [plugin.py#L58](https://github.com/zhaoterryy/mkdocs-git-revision-date-plugin/blob/master/mkdocs_git_revision_date_plugin/plugin.py#L58)).

I had a similar issue in [mkdocs-git-revision-date-localized-plugin](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin) and solved it by replacing it with a regex ([code](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/master/mkdocs_git_revision_date_localized_plugin/plugin.py#L67))

I'll contribute a PR back to `mkdocs-git-revision-date-plugin`, and if @zhaoterryy accepts, best case it solves your problem, worst case you'll know better where to look 😄
